#!/usr/bin/env python

import click

from tweet_dns.configuration import config

@click.group()
def cli():
    pass

@click.command()
@click.argument('keys', nargs=-1)
def get(keys):
    config.load()
    try:
        print config.get(*keys)
    except KeyError, e:
        print "Error: '%s' is not set." % keys

@click.command()
@click.argument('keys', nargs=-1, required=True)
@click.argument('value', nargs=1, required=True)
def set(keys, value):
    config.load()
    print "setting '%s' to '%s'" % (str(keys), str(value))
    config.set(*(keys + (value,)))
    config.save()
    print "done."

@click.command()
def show():
    config.load()
    print config._tree

@click.command()
@click.confirmation_option(help='Are you sure you want to clear the Clacks settings file?')
def clear():
    print "clearing Clacks Config.."
    config.load()
    config._tree = {}
    config.save()
    print "cleared."

if __name__ == '__main__':
    cli.add_command(get)
    cli.add_command(set)
    cli.add_command(show)
    cli.add_command(clear)

    cli()
